import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import "@fontsource/lobster"; // Import Lobster font
import NavBar from "@/components/ui/navbar/NavBar";
import { ThemeProvider } from "@/utils/ThemeProvider";
import {
  UserContextProvider,
  DisablerContextProvider,
  WorkProfileContextProvider,
} from "@/utils/context/contextProviders";
import { Toaster } from "@/components/ui/toaster";
import RouteProtection from "@/utils/manageRoutes/RouteProtection";

const nunito = Nunito_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className} `}>
        <main>
          <DisablerContextProvider>
            <UserContextProvider>
              <WorkProfileContextProvider>
                <ThemeProvider
                  attribute="class"
                  defaultTheme="dark"
                  enableSystem
                  disableTransitionOnChange
                >
                  <RouteProtection>
                    <NavBar />

                    {children}
                  </RouteProtection>
                  <Toaster />
                </ThemeProvider>
              </WorkProfileContextProvider>
            </UserContextProvider>
          </DisablerContextProvider>
        </main>
      </body>
    </html>
  );
}
