import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import "@fontsource/lobster"; // Import Lobster font
import NavBar from "@/components/ui/navbar/NavBar";
import { ThemeProvider } from "@/utils/ThemeProvider";
import {
  UserContextProvider,
  DisablerContextProvider,
} from "@/utils/context/contextProviders";

const nunito = Nunito_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className} `}>
        <DisablerContextProvider>
          <UserContextProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
            >
              <NavBar />

              {children}
            </ThemeProvider>
          </UserContextProvider>
        </DisablerContextProvider>
      </body>
    </html>
  );
}
