import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import "@fontsource/lobster"; // Import Lobster font
import NavBar from "@/components/navbar/NavBar";
import { ThemeProvider } from "@/utils/ThemeProvider";
import {
  UserContextProvider,
  DisablerContextProvider,
  WorkProfileContextProvider,
  SubscriptionContextProvider,
} from "@/utils/context/stateContextProviders";
import { Toaster } from "@/components/ui/toaster";
import RouteProtection from "@/utils/controllers/RouteProtection";
import UserInjector from "@/utils/controllers/userInjector";
import PromoBar from "@/components/promotionBar/promoBar";


import { NotificationSheet } from "@/components/NotificationSheet/NotificationSheet";
import { VideoChatSocketProvider } from "@/utils/context/videoChatSocketContext";
import { NotificationProvider } from "@/utils/context/NotificationContext";

const nunito = Nunito_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className} `}>
        <main className="px-5 md:px-10">
          <DisablerContextProvider>
            <UserContextProvider>
              <SubscriptionContextProvider>
                <UserInjector>
                  <RouteProtection>
                    <NotificationProvider>
                      <WorkProfileContextProvider>
                       
                          <ThemeProvider
                            attribute="class"
                            defaultTheme="dark"
                            enableSystem
                            disableTransitionOnChange
                          >
                            <NavBar />
                            <NotificationSheet />

                            {children}
                            <Toaster />
                          </ThemeProvider>
                      
                      </WorkProfileContextProvider>
                    </NotificationProvider>
                  </RouteProtection>
                </UserInjector>
              </SubscriptionContextProvider>
            </UserContextProvider>
          </DisablerContextProvider>
        </main>
      </body>
    </html>
  );
}
